name: CI/CD MySQL Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: rootpassword
          MYSQL_DATABASE: testdb
          MYSQL_USER: testuser
          MYSQL_PASSWORD: testpassword
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install MySQL connector
        run: |
          python -m pip install --upgrade pip
          pip install mysql-connector-python

      - name: Run SQL Script
        env:
          DB_HOST: localhost
          DB_USER: testuser
          DB_PASSWORD: testpassword
          DB_NAME: testdb
        run: |
          python execute_sql_script.py add_departments.sql "$DB_HOST" "$DB_USER" "$DB_PASSWORD" "$DB_NAME"
